version: '3.8'

services:
  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: flight-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ubuntu.conf:/etc/nginx/conf.d/default.conf
      - ./Front_end/build:/var/www/html/flight-frontend
      - ./ssl:/etc/nginx/ssl  # SSL 证书目录 (可选)
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - flight-network

  # 后端服务
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: flight-backend
    ports:
      - "38181:38181"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=38181
    env_file:
      - ./.env
    volumes:
      - ./Backend/instance:/app/instance
      - ./Backend/logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - flight-network

  # 数据库 (可选，如果使用 PostgreSQL)
  # postgres:
  #   image: postgres:13
  #   container_name: flight-postgres
  #   environment:
  #     POSTGRES_DB: flight_monitor
  #     POSTGRES_USER: flight_user
  #     POSTGRES_PASSWORD: your_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - flight-network

networks:
  flight-network:
    driver: bridge

volumes:
  postgres_data:  # 如果使用 PostgreSQL
  nginx_logs:     # Nginx 日志卷
