version: '3.8'

services:
  ticketradar:
    build: .
    container_name: ticketradar-app
    restart: unless-stopped
    ports:
      - "38181:38181"
    env_file:
      - .env.docker
    volumes:
      - ticketradar_data:/app
    networks:
      - ticketradar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:38181/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: ticketradar-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ticketradar
    networks:
      - ticketradar-network
    profiles:
      - nginx

volumes:
  ticketradar_data:
    driver: local

networks:
  ticketradar-network:
    driver: bridge
