version: '3.8'

services:
  ticketradar:
    build: .
    container_name: ticketradar-app
    restart: unless-stopped
    ports:
      - "38181:38181"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=38181
      - SECRET_KEY=docker-ticketradar-secret-key-change-this
      - DATABASE_URL=sqlite:///data/ticketradar.db
      - ENABLE_PUSHPLUS=false
      - PUSHPLUS_TOKEN=
      - PRICE_THRESHOLD=1000
      - CHECK_INTERVAL=5
      - DEFAULT_DEPARTURE=HKG
      - TRIP_TYPE=2
      - DEPART_DATE=2025-09-30
      - RETURN_DATE=2025-10-08
    volumes:
      - ticketradar_data:/app/data
      - ticketradar_logs:/app/logs
    networks:
      - ticketradar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:38181/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: ticketradar-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ticketradar
    networks:
      - ticketradar-network
    profiles:
      - nginx

volumes:
  ticketradar_data:
    driver: local
  ticketradar_logs:
    driver: local

networks:
  ticketradar-network:
    driver: bridge
